{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.security.serviceSecretName }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  {{ .Values.security.provisioningServiceTokenKey }}: {{ .Values.secrets.provisioningServiceToken | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.provisioning.providerSecretName }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  {{ .Values.provisioning.digitalOceanTokenKey }}: {{ .Values.secrets.digitalOceanToken | quote }}
  {{ .Values.provisioning.runpodApiKeyKey }}: {{ .Values.secrets.runpodApiKey | quote }}
{{- end }}
