import { DemoInstance, DeployCatalogItem } from "./types";

export const countryOptions = [
  { value: "BY", label: "Belarus (BY)" },
  { value: "RU", label: "Russia (RU)" },
  { value: "KZ", label: "Kazakhstan (KZ)" },
  { value: "DE", label: "Germany (DE)" },
  { value: "NL", label: "Netherlands (NL)" },
  { value: "US", label: "United States (US)" },
  { value: "CA", label: "Canada (CA)" },
  { value: "SG", label: "Singapore (SG)" }
] as const;

export const deployCatalog: DeployCatalogItem[] = [
  { id: "cat-01", gpuModel: "RTX 3060", vramGb: 12, vcpu: 8, ramGb: 24, country: "BY", region: "eu-central", datacenter: "MNS-1", pricePerHour: 0.18, availability: "high", networkFeatures: ["IPv4", "SSH"], computeType: "GPU" },
  { id: "cat-02", gpuModel: "RTX 4090", vramGb: 24, vcpu: 16, ramGb: 48, country: "RU", region: "eu-east", datacenter: "MSK-3", pricePerHour: 0.85, availability: "medium", networkFeatures: ["IPv4", "IPv6", "SR-IOV"], computeType: "GPU" },
  { id: "cat-03", gpuModel: "A100", vramGb: 80, vcpu: 24, ramGb: 96, country: "KZ", region: "asia-west", datacenter: "ALA-2", pricePerHour: 2.15, availability: "medium", networkFeatures: ["IPv4", "Private VPC"], computeType: "GPU" },
  { id: "cat-04", gpuModel: "H100 x2", vramGb: 160, vcpu: 48, ramGb: 192, country: "DE", region: "eu-west", datacenter: "FRA-1", pricePerHour: 4.5, availability: "low", networkFeatures: ["IPv4", "IPv6", "Private VPC"], computeType: "GPU" },
  { id: "cat-05", gpuModel: "RTX 3060", vramGb: 12, vcpu: 8, ramGb: 16, country: "NL", region: "eu-west", datacenter: "AMS-1", pricePerHour: 0.24, availability: "high", networkFeatures: ["IPv4", "SSH"], computeType: "GPU" },
  { id: "cat-06", gpuModel: "RTX 4090", vramGb: 24, vcpu: 12, ramGb: 32, country: "US", region: "us-east", datacenter: "IAD-2", pricePerHour: 1.05, availability: "high", networkFeatures: ["IPv4", "IPv6"], computeType: "GPU" },
  { id: "cat-07", gpuModel: "A100", vramGb: 80, vcpu: 20, ramGb: 80, country: "CA", region: "ca-central", datacenter: "YUL-1", pricePerHour: 2.45, availability: "medium", networkFeatures: ["IPv4", "VPC"], computeType: "GPU" },
  { id: "cat-08", gpuModel: "H100 x2", vramGb: 160, vcpu: 40, ramGb: 160, country: "SG", region: "ap-southeast", datacenter: "SGP-1", pricePerHour: 4.1, availability: "low", networkFeatures: ["IPv4", "IPv6", "Private VPC"], computeType: "GPU" },
  { id: "cat-09", gpuModel: "CPU Optimized", vramGb: 0, vcpu: 16, ramGb: 64, country: "DE", region: "eu-west", datacenter: "MUC-4", pricePerHour: 0.55, availability: "high", networkFeatures: ["IPv4", "IPv6"], computeType: "CPU" },
  { id: "cat-10", gpuModel: "CPU Balanced", vramGb: 0, vcpu: 8, ramGb: 32, country: "US", region: "us-west", datacenter: "SJC-1", pricePerHour: 0.37, availability: "high", networkFeatures: ["IPv4"], computeType: "CPU" }
];

export const demoInstances: DemoInstance[] = [
  { id: "inst-001", name: "train-vision-small-01", created_at: "2026-02-01T09:12:00Z", uptime: "3d 11h", last_action: "start", cost_to_date: 14.22, status: "running", country: "BY", size: "Small", gpuModel: "RTX 3060", vramGb: 12, pricePerHour: 0.18, endpoints: ["https://inst-001.sharemtc.ai", "10.11.0.21:22"], sshCommand: "ssh ubuntu@inst-001.sharemtc.ai", lastEvents: ["Container started", "Weights synced"], billingSummary: { onDemandHours: 79, spotHours: 0, total: 14.22 }, warnings: [], slaAvailability: "99.9%" },
  { id: "inst-002", name: "llm-medium-ru-02", created_at: "2026-02-04T12:47:00Z", uptime: "1d 03h", last_action: "deploy", cost_to_date: 20.4, status: "provisioning", country: "RU", size: "Medium", gpuModel: "RTX 4090", vramGb: 24, pricePerHour: 0.85, endpoints: ["pending"], sshCommand: "pending", lastEvents: ["Image pull started", "Waiting for GPU slot"], billingSummary: { onDemandHours: 24, spotHours: 0, total: 20.4 }, warnings: ["Insufficient capacity in selected region"], slaAvailability: "99.5%" },
  { id: "inst-003", name: "ranker-large-kz", created_at: "2026-01-22T06:15:00Z", uptime: "0d 00h", last_action: "stop", cost_to_date: 58.9, status: "stopped", country: "KZ", size: "Large", gpuModel: "A100", vramGb: 80, pricePerHour: 2.15, endpoints: ["https://inst-003.sharemtc.ai"], sshCommand: "ssh root@inst-003.sharemtc.ai", lastEvents: ["Stopped by user"], billingSummary: { onDemandHours: 20, spotHours: 7, total: 58.9 }, warnings: [], slaAvailability: "99.9%" },
  { id: "inst-004", name: "train-xl-de-04", created_at: "2026-02-10T03:31:00Z", uptime: "6h 14m", last_action: "reboot", cost_to_date: 27.0, status: "running", country: "DE", size: "XL", gpuModel: "H100 x2", vramGb: 160, pricePerHour: 4.5, endpoints: ["https://inst-004.sharemtc.ai"], sshCommand: "ssh ml@inst-004.sharemtc.ai", lastEvents: ["Reboot complete", "CUDA cache warmed"], billingSummary: { onDemandHours: 6, spotHours: 0, total: 27.0 }, warnings: [], slaAvailability: "99.95%" },
  { id: "inst-005", name: "batch-small-nl", created_at: "2026-01-30T22:00:00Z", uptime: "2d 08h", last_action: "start", cost_to_date: 18.52, status: "running", country: "NL", size: "Small", gpuModel: "RTX 3060", vramGb: 12, pricePerHour: 0.24, endpoints: ["https://inst-005.sharemtc.ai"], sshCommand: "ssh deploy@inst-005.sharemtc.ai", lastEvents: ["Queue drained"], billingSummary: { onDemandHours: 77, spotHours: 0, total: 18.52 }, warnings: [], slaAvailability: "99.9%" },
  { id: "inst-006", name: "api-medium-us", created_at: "2026-02-06T15:08:00Z", uptime: "0d 17h", last_action: "deploy", cost_to_date: 12.14, status: "error", country: "US", size: "Medium", gpuModel: "RTX 4090", vramGb: 24, pricePerHour: 1.05, endpoints: ["n/a"], sshCommand: "n/a", lastEvents: ["Boot failed", "Kernel module mismatch"], billingSummary: { onDemandHours: 11, spotHours: 0, total: 12.14 }, warnings: ["CUDA mismatch"], slaAvailability: "98.0%" },
  { id: "inst-007", name: "recsys-large-ca", created_at: "2026-01-28T11:54:00Z", uptime: "4d 02h", last_action: "start", cost_to_date: 240.1, status: "running", country: "CA", size: "Large", gpuModel: "A100", vramGb: 80, pricePerHour: 2.45, endpoints: ["https://inst-007.sharemtc.ai"], sshCommand: "ssh ubuntu@inst-007.sharemtc.ai", lastEvents: ["Autoscaling disabled"], billingSummary: { onDemandHours: 98, spotHours: 0, total: 240.1 }, warnings: [], slaAvailability: "99.95%" },
  { id: "inst-008", name: "vision-xl-sg", created_at: "2026-02-12T02:17:00Z", uptime: "0d 05h", last_action: "deploy", cost_to_date: 9.1, status: "interrupted", country: "SG", size: "XL", gpuModel: "H100 x2", vramGb: 160, pricePerHour: 4.1, endpoints: ["https://inst-008.sharemtc.ai"], sshCommand: "ssh root@inst-008.sharemtc.ai", lastEvents: ["Spot interruption notice", "Node preempted"], billingSummary: { onDemandHours: 0, spotHours: 2.2, total: 9.1 }, warnings: ["Auth required"], slaAvailability: "97.9%" },
  { id: "inst-009", name: "embed-small-de", created_at: "2026-02-11T20:09:00Z", uptime: "0d 00h", last_action: "deploy", cost_to_date: 0.0, status: "queued", country: "DE", size: "Small", gpuModel: "RTX 3060", vramGb: 12, pricePerHour: 0.2, endpoints: ["pending"], sshCommand: "pending", lastEvents: ["Queued for host assignment"], billingSummary: { onDemandHours: 0, spotHours: 0, total: 0.0 }, warnings: ["SSH key missing"], slaAvailability: "n/a" },
  { id: "inst-010", name: "chat-medium-ru", created_at: "2026-01-15T18:31:00Z", uptime: "12d 06h", last_action: "reboot", cost_to_date: 244.8, status: "running", country: "RU", size: "Medium", gpuModel: "RTX 4090", vramGb: 24, pricePerHour: 0.8, endpoints: ["https://inst-010.sharemtc.ai"], sshCommand: "ssh root@inst-010.sharemtc.ai", lastEvents: ["Patch applied", "Service healthy"], billingSummary: { onDemandHours: 306, spotHours: 0, total: 244.8 }, warnings: [], slaAvailability: "99.7%" },
  { id: "inst-011", name: "finetune-large-us", created_at: "2026-02-03T05:02:00Z", uptime: "3d 22h", last_action: "start", cost_to_date: 219.6, status: "running", country: "US", size: "Large", gpuModel: "A100", vramGb: 80, pricePerHour: 2.3, endpoints: ["https://inst-011.sharemtc.ai"], sshCommand: "ssh ml@inst-011.sharemtc.ai", lastEvents: ["Checkpoint synced"], billingSummary: { onDemandHours: 95, spotHours: 1, total: 219.6 }, warnings: [], slaAvailability: "99.95%" },
  { id: "inst-012", name: "render-xl-nl", created_at: "2026-02-02T10:42:00Z", uptime: "0d 00h", last_action: "deploy", cost_to_date: 33.4, status: "error", country: "NL", size: "XL", gpuModel: "H100 x2", vramGb: 160, pricePerHour: 4.2, endpoints: ["n/a"], sshCommand: "n/a", lastEvents: ["Init container failed", "Authorization denied"], billingSummary: { onDemandHours: 7, spotHours: 1, total: 33.4 }, warnings: ["Auth required"], slaAvailability: "96.4%" }
];
